import lrrbot.commands.card
import lrrbot.commands.explain
import lrrbot.commands.game
import lrrbot.commands.highlights
import lrrbot.commands.lockdown
import lrrbot.commands.misc
import lrrbot.commands.show
import lrrbot.commands.static
import lrrbot.commands.stats
import lrrbot.commands.strawpoll
import lrrbot.commands.quote
import lrrbot.commands.codefall
