import commands.game
import commands.stats
import commands.static
import commands.misc
import commands.explain
import commands.card
import commands.highlights
import commands.lockdown
import commands.show
